import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto_Slab, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { UnderConstructionPopup } from "@/components/temp/underConstruction";
<<<<<<< HEAD
import { FavoritesProvider } from "@/lib/context/favorites-context";
import CartDrawer from "@/components/cart/favorites-drawer";
=======
import { CartProvider } from "@/lib/context/cart-context";
import CartDrawer from "@/components/cart/cart-drawer";
import { AuthProvider } from "@/lib/context/auth-context";
import AuthModal from "@/components/auth/auth-modal";
>>>>>>> d785179fef0256701e4716f7cc2c24e75284244c

const robotoSlabHeading = Roboto_Slab({ subsets: ['latin'], variable: '--font-heading' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontHeading = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, robotoSlabHeading.variable, fontHeading.variable)}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        { /*Deze under construction popup kan ik later weer weghalen ;)*/}
<<<<<<< HEAD
        <FavoritesProvider>
          <UnderConstructionPopup />

          <Header />
          {children}
          <Footer /> 
          <CartDrawer />
        </FavoritesProvider>
=======
        <CartProvider>
          <AuthProvider>
            <UnderConstructionPopup />

            <Header />
            {children}
            <Footer />
            <CartDrawer />
            <AuthModal />
          </AuthProvider>
        </CartProvider>
>>>>>>> d785179fef0256701e4716f7cc2c24e75284244c
      </body>
    </html>
  );
}
